# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "36258e9b96319d13c87a537487b91859"
application_url = "https://popup-pop.vercel.app/app"
embedded = true
name = "popup-pop"

[access_scopes]
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://popup-pop.vercel.app/auth/callback",
  "https://popup-pop.vercel.app/auth"
]

[webhooks]
api_version = "2026-04"
